<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1586911819716" stop="1586911837052">
    <name>Default Suite</name>
    <test-cases>
        <test-case start="1586911820899" stop="1586911836995" status="broken">
            <name>feature[Groups]</name>
            <failure>
                <message>CucumberException: java.lang.AssertionError: 
Expected: &lt;[GroupData{id='2147483647', name='xxx'}, GroupData{id='341', name='test1'}, GroupData{id='340', name='test93'}, GroupData{id='342', name='test name'}]&gt;
     but: was &lt;[GroupData{id='341', name='test1'}, GroupData{id='340', name='test93'}, GroupData{id='343', name='xxx'}, GroupData{id='342', name='test name'}]&gt;</message>
                <stack-trace>cucumber.runtime.CucumberException: java.lang.AssertionError: 
Expected: &lt;[GroupData{id='2147483647', name='xxx'}, GroupData{id='341', name='test1'}, GroupData{id='340', name='test93'}, GroupData{id='342', name='test name'}]&gt;
     but: was &lt;[GroupData{id='341', name='test1'}, GroupData{id='340', name='test93'}, GroupData{id='343', name='xxx'}, GroupData{id='342', name='test name'}]&gt;
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: java.lang.AssertionError: 
Expected: &lt;[GroupData{id='2147483647', name='xxx'}, GroupData{id='341', name='test1'}, GroupData{id='340', name='test93'}, GroupData{id='342', name='test name'}]&gt;
     but: was &lt;[GroupData{id='341', name='test1'}, GroupData{id='340', name='test93'}, GroupData{id='343', name='xxx'}, GroupData{id='342', name='test name'}]&gt;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at com.andrey.addressbook.bdd.GroupStepDefinitions.verifyGroupCreated(GroupStepDefinitions.java:55)
	at âœ½.Then the new set if groups is equal to the old set with the added group(bdd/groups.feature:6)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels/>
        </test-case>
    </test-cases>
    <labels/>
</ns2:test-suite>
